repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: check-added-large-files
  - id: double-quote-string-fixer
  - id: forbid-new-submodules

- repo: git://github.com/pre-commit/mirrors-yapf
  rev: v0.28.0
  hooks:
  - id: yapf
    language: system
    types: [python]

- repo: https://github.com/PyCQA/prospector
  rev: 1.1.7
  hooks:
  - id: prospector
    language: system
    types: [python]

- repo: local
  hooks:
  - id: travis-linter
    name: travis
    entry: travis lint
    files: .travis.yml
    language: ruby
    additional_dependencies: ['travis']
